### ISSUE TITLE
Change validate error text

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-towerdata#17]
This integration should skip with the reason "Missing credentials, contact ActiveProspect support" reason when credential environment variables are missing. The [current reason given](https://github.com/activeprospect/leadconduit-integration-towerdata/blob/027a3501824f0d82527e6c8bd6653cac3cea144e/src/outbound.coffee#L159) is 'missing API key - please contact support@activeprospect.com'. We want it to be consistent with the same message given by other integrations.

**Comment by ros3bud** [comment]
This is in 1.2.1
