### ISSUE TITLE
integration error

### ISSUE THREAD

**Issue by zalary** [activeprospect/leadconduit-integration-towerdata#2]
This integration is currently erroring with the following reason:

TowerData Outcome	error
TowerData Reason	Cannot read property 'length' of undefined

I think this is related to the apiKey env variable but haven't been able to pinpoint the exact issue.

cc @alexkwolfe

**Comment by alexkwolfe** [comment]
It's probably worth checking `process.env.TOWER_DATA_API_KEY` to ensure that a value is set. That could go in the `validate()` function.

**Comment by zalary** [comment]
fixed by PR #2 #3 and #4 (took a few tries to get it right)
